/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Administrator
 */

public class AplikasiPenampilGambar extends javax.swing.JFrame {
   
    /**
     * Creates new form AplikasiPenampilGambar
     */
    public AplikasiPenampilGambar() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonpanel = new javax.swing.JPanel();
        cbbx = new javax.swing.JComboBox<>();
        btnblack = new javax.swing.JButton();
        btnbalon = new javax.swing.JButton();
        btnCafe = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        black = new javax.swing.JLabel();
        balon = new javax.swing.JLabel();
        cafe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        buttonpanel.setMaximumSize(new java.awt.Dimension(300, 400));
        buttonpanel.setMinimumSize(new java.awt.Dimension(300, 400));
        buttonpanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 100, 100));

        cbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Ballon", "Cafe" }));
        cbbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbxItemStateChanged(evt);
            }
        });
        buttonpanel.add(cbbx);

        btnblack.setText("Black");
        btnblack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblackActionPerformed(evt);
            }
        });
        buttonpanel.add(btnblack);

        btnbalon.setText("Balon");
        btnbalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbalonActionPerformed(evt);
            }
        });
        buttonpanel.add(btnbalon);

        btnCafe.setText("Cafe");
        btnCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCafeActionPerformed(evt);
            }
        });
        buttonpanel.add(btnCafe);

        btnexit.setText("exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        buttonpanel.add(btnexit);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.CENTER);

        imagepanel.setLayout(new java.awt.CardLayout(316, 0));

        black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/pexels-ivan-siarbolin-3695801.jpg"))); // NOI18N
        black.setText("black");
        black.setMaximumSize(new java.awt.Dimension(316, 400));
        black.setMinimumSize(new java.awt.Dimension(316, 400));
        black.setPreferredSize(new java.awt.Dimension(316, 400));
        imagepanel.add(black, "0");
        black.getAccessibleContext().setAccessibleName("0");

        balon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/pexels-ash-valiente-3533228 (2).jpg"))); // NOI18N
        balon.setText("black");
        balon.setMaximumSize(new java.awt.Dimension(316, 400));
        balon.setMinimumSize(new java.awt.Dimension(316, 400));
        balon.setPreferredSize(new java.awt.Dimension(316, 400));
        imagepanel.add(balon, "1");

        cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/pexels-cottonbro-studio-4543103.jpg"))); // NOI18N
        cafe.setText("black");
        cafe.setMaximumSize(new java.awt.Dimension(316, 400));
        cafe.setMinimumSize(new java.awt.Dimension(316, 400));
        cafe.setPreferredSize(new java.awt.Dimension(316, 400));
        imagepanel.add(cafe, "2");

        getContentPane().add(imagepanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnblackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblackActionPerformed
    CardLayout cl = (CardLayout)(imagepanel.getLayout());
    cl.show(imagepanel, "0");
    }//GEN-LAST:event_btnblackActionPerformed

    private void btnbalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbalonActionPerformed
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
    cl.show(imagepanel, "1");
    }//GEN-LAST:event_btnbalonActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCafeActionPerformed
         CardLayout cl = (CardLayout)(imagepanel.getLayout());
    cl.show(imagepanel, "2");
    }//GEN-LAST:event_btnCafeActionPerformed

    private void cbbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbxItemStateChanged
      CardLayout cl= (CardLayout)(imagepanel.getLayout());
      cl.show(imagepanel, String.valueOf(cbbx.getSelectedIndex()));
    }//GEN-LAST:event_cbbxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(new Runnable(){
     public void run(){
     AplikasiPenampilGambar fullframe = new AplikasiPenampilGambar();
         GraphicsDevice device=
                 GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
         device.setFullScreenWindow(fullframe);
         fullframe.setVisible(true);
     }
    });
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balon;
    private javax.swing.JLabel black;
    private javax.swing.JButton btnCafe;
    private javax.swing.JButton btnbalon;
    private javax.swing.JButton btnblack;
    private javax.swing.JButton btnexit;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JLabel cafe;
    private javax.swing.JComboBox<String> cbbx;
    private javax.swing.JPanel imagepanel;
    // End of variables declaration//GEN-END:variables
}
